# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lizette Vázquez González
title: Ingeniera en informatica
email: golivaxd@gmail.com
website: https://xxgolivaxx.github.io/CV/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: goliva_xd
github_username:  XxGolivaxX
# stackoverflow_username: "00000001"
# dribbble_username: goliva
# facebook_username: goliva
# flickr_username: goliva
instagram_username: goliva_xd
linkedin_username: golivaxd
# xing_username: goliva
# pinterest_username: goliva
# youtube_username: NA
# googleplus_username: goliva
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: My page
  icon: fas fa-globe
  url: https://xxgolivaxx.github.io/goliva/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hola, soy Lizette, estudiante de Ingeniería Informática. 
 Me considero una persona responsable, dedicada, y con facilidad para adaptarme a nuevos entornos. Disfruto trabajar en equipo y tengo una gran capacidad de aprendizaje. Además, soy hábil para resolver problemas y enfrentar desafíos de manera eficiente.

#Soy muy habil en: <mark></mark> and <mark>Playing videogames</mark>

content:
  - title: Certificados # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Algunos cursos
        link: https://www.linkedin.com/in/golivaxd/
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Learn and improve
        description: | # this will include new lines to allow paragraphs
          Estos son algunos de los cursos que e tomado. 
          #   icon: fab fa-github
          #   url: https://courses.cognitiveclass.ai/certificates/a35949ad297343709fdaa06811b330b1
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierias
        caption: 2020 - present
        sub_title: Computer Engineering
        quote: >
          CUCEI was created in 1994, based on the old faculties of Sciences, Chemical Sciences, Informatics and Computing and Engineering; in addition to the Wood, Pulp and Paper Institutes; Astronomy and Meteorology (IAM) and the Directorate of Linkage and Technology Transfer.
        description: | # this will include new lines to allow paragraphs
          I am currently a student and I spent most of my time studying, I consider this stage to be one of the most important since the effort I give is what defines my knowledge, so I try to be dedicated with this.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer engineering some of my other interests and hobbies are:
      - Playing videogames
      - Ride a bike
      - Drawing
      - [Listen to my favorite artist](https://youtube.com/playlist?list=OLAK5uy_mG42_gxfZ-Cq6Y921XWm43Z75YAiaSIWI&si=NepL5ibwB2ItaEmW)

      Look at this animation made by me
      ![Pumpkin](/modern-resume-theme/images/CalabazaG1.jpg"Pumpkin")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
