# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lizette Vázquez González
title: Ingeniera en Informática
email: golivaxd@gmail.com
website: https://xxgolivaxx.github.io/CV/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: goliva_xd
github_username:  XxGolivaxX
instagram_username: goliva_xd
linkedin_username: golivaxd

# Additional icon links
additional_links:
- title: My page
  icon: fas fa-globe
  url: https://xxgolivaxx.github.io/goliva/

# About Section
about_title: Sobre mí
about_profile_image: images/profile.jpg
about_content: | 
  Hola, soy Lizette, estudiante de Ingeniería Informática. 
  Me considero una persona responsable, dedicada, y con facilidad para adaptarme a nuevos entornos. Disfruto trabajar en equipo y tengo una gran capacidad de aprendizaje. Además, soy hábil para resolver problemas y enfrentar desafíos de manera eficiente.

# Resumen Profesional
  - title: Resumen Profesional
    layout: text
    content: | 
      Soy estudiante de Ingeniería en Informática con sólidos conocimientos en desarrollo web (HTML, CSS, JavaScript) y un interés constante por el aprendizaje continuo. Me motiva contribuir y crecer en la industria tecnológica, mientras desarrollo mis habilidades en programación y diseño de videojuegos.

# Habilidades
  - title: Habilidades
    layout: list
    content:
      - title: HTML, CSS, JavaScript
        sub_title: Desarrollo web
        description: | 
          Tengo experiencia en la creación de sitios web utilizando HTML, CSS y JavaScript. Estoy en proceso de aprender frameworks como React para mejorar mis habilidades de desarrollo frontend.
      
      - title: Game Development
        sub_title: Desarrollo de videojuegos
        description: |
          Interesada en el desarrollo de videojuegos. Experiencia básica en el uso de motores de juegos como Unity.

# Proyectos
  - title: Proyectos
    layout: list
    content:
      - layout: top-middle
        title: Animación Pumpkin
        link: https://xxgolivaxx.github.io/animation
        quote: |
          Desarrollo de una animación en Adobe After Effects.
        description: | 
          Creé una animación corta como parte de un proyecto personal, donde pude aplicar mis habilidades en diseño y animación.

# Certificados
  - title: Certificados
    layout: list
    content:
      - layout: top-middle
        title: Algunos cursos
        link: https://www.linkedin.com/in/golivaxd/
        quote: >
          Learn and improve
        description: | 
          Estos son algunos de los cursos que he tomado.

# Educación
  - title: Educación
    layout: list
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        caption: 2020 - present
        sub_title: Ingeniería Informática
        description: | 
          Actualmente soy estudiante en CUCEI, dedicando gran parte de mi tiempo a adquirir conocimientos que me permitan desarrollarme como profesional en el ámbito de la informática.

# Aficiones e Intereses
  - title: Aficiones e Intereses
    layout: text
    content: | 
      Además de mis intereses en ingeniería informática, algunos de mis otros intereses y pasatiempos son:
      - Jugar videojuegos.
      - Andar en bicicleta.
      - Dibujar.
      - [Escuchar a mi artista favorito](https://youtube.com/playlist?list=OLAK5uy_mG42_gxfZ-Cq6Y921XWm43Z75YAiaSIWI&si=NepL5ibwB2ItaEmW)
      - Mira esta animación hecha por mí:
        ![Pumpkin](/modern-resume-theme/images/CalabazaG1.jpg "Pumpkin")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
